### ISSUE TITLE
Training issue

### ISSUE THREAD

**Issue by AselSiriwardena** [aasharma90/RetinexNet_PyTorch#1]
First, thank you for making the PyTorch model for RetinexNet!
I have trying to train this model with an RTX 3080 GPU with default configs. But I got this error. Then I have changes batch size to 1 and now it's working, But it's not completely utilizing my GPU, Only 3-4  percent. 

```
Number of training data: 1485
Model restore success!
Start training for phase Decom, with start epoch 260 start iter 19305 :
Finished training for phase Decom.
No pretrained model to restore!
Start training for phase Relight, with start epoch 0 start iter 0 :
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    train(model)
  File "train.py", line 66, in train
    train_phase="Relight")
  File "C:\Users\User\Desktop\RetinexNet_PyTorch\model.py", line 336, in train
    self.loss_Relight.backward()
  File "C:\Users\User\anaconda3\envs\Python37\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "C:\Users\User\anaconda3\envs\Python37\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by aasharma90** [comment]
Hi @AselSiriwardena 

Thanks for your feedback. 
I've not observed this error before. Have you tried testing the code before training it, i.e. testing using the provided pre-trained checkpoint?

**Comment by aasharma90** [comment]
Hi, since I didn't hear anything back, closing this due to lack of activity.
